version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    hostname: es01
    environment:
        - node.name=es01
        - node.master=true
        - cluster.name=cluster
        - discovery.seed_hosts=es02
        # - bootstrap.memory_lock=true
        # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits:
    #     memlock:
    #         soft: -1
    #         hard: -1
    ports:
        - 9200:9200
    # volumes:
    #     - elastic-1-data:/usr/share/elasticsearch/data
    extra_hosts:
      - "es2:10.10.0.1"