version: '3.7'
services:
  hadoop-master:
    image: hadoop
    hostname: hadoop-master
    ports:
      - 9000:9000
      - 8088:8088
      - 8032:8032
      - 9870:9870
    volumes: 
      - type: bind
        source: /mnt/4E9A200D9A1FF067/University/20202/GR/data/hadoop/name
        target: /dfs/name
      - type: bind
        source: /mnt/4E9A200D9A1FF067/University/20202/GR/data/hadoop/data
        target: /dfs/data